# Generated by Django 4.0.4 on 2022-05-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cars',
            new_name='car',
        ),
    ]
