# Generated by Django 4.0.4 on 2022-05-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsModel', '0003_alter_car_seat_alter_car_yearofmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='car',
            name='yearOfModel',
        ),
    ]
